### ISSUE TITLE
client.remoteUsers not wroking

### ISSUE THREAD

**Issue by shreyas-jadhav** [AgoraIO/API-Examples-Web#10]
Hey, I'm not using TypeScript here, but in my Next.js project, I'm constantly getting an empty array when I `Array.from(client.remoteUsers)`.
Basically, I wanted to filter out some users by username, but I can't even access the array as I am getting `client.remoteUsers` as a typeof `object`.

I am stuck here from nearly 2 days. I don't understand what i'm doing wrong here. Console logging `client.remoteUsers` actually returns me an array. I cannot map / filter / Array.from() or any other operation. It's returning me an empty array.

```js

const newA = client.remoteUsers.map((user)=>{
      return {videoTrack: user.videoTrack, audioTrack: user.audioTrack}
    });

console.log(newA) //empty even though it;s not.

setStudents(remoteUsers => Array.from(client.remoteUsers)); 

console.log(students); //empty array even though it;s not.

```

**Comment by yoreland** [comment]
just a quick check，did you try the same on client.on("user-published") callback?

**Comment by shreyas-jadhav** [comment]
Yes. When I console log only the `user` I get the user. But I'm not able to add it to an array, or acces it's properties like `user.uid` etc.

Moment I add it to an array, immediately returns an empty array.

**Comment by plutoless** [comment]
what is the implementation of setStudents?
