### ISSUE TITLE
Error publishing on Agora Web SDK v4

### ISSUE THREAD

**Issue by sambhavsharma** [AgoraIO/API-Examples-Web#12]
I followed the steps as mentioned in the docs. I was earlier using agora v3.6.0 and everything was working fine. I want to upgrade to Agora v4 which isn't backward compatible, but looked easy enough to implement.

I am receiving the following error after I publish my local tracks.

```
AgoraRTC_N-production.js:637 Uncaught (in promise) TypeError: this.report.forEach is not a function
    at b.<anonymous> (AgoraRTC_N-production.js:637)
    at AgoraRTC_N-production.js:175
    at Object.next (AgoraRTC_N-production.js:176)
    at g (AgoraRTC_N-production.js:174)
```

-- Code

`
        import AgoraRTC from 'agora-rtc-sdk-ng';
        const AgoraClient = AgoraRTC.createClient({ mode: 'rtc', codec: "h264" });
       

        // inside useEffect.
        const agoraAccessToken = await actions.auth.getAgoraAccessToken({ requestParams: {channel: props.config.channel}});
        let uid = await AgoraClient.join(props.config.appId, props.config.channel, agoraAccessToken);

        let audioTrack = await AgoraRTC.createMicrophoneAudioTrack();
        let videoTrack = await AgoraRTC.createCameraVideoTrack();

        await AgoraClient.publish([audioTrack, videoTrack]);
`

**Comment by yoreland** [comment]
Hi, it is a bit hard to check the issue from this message only. If it is possible can you upload part of your code which could reproduce the issue?

**Comment by sambhavsharma** [comment]
> Hi, it is a bit hard to check the issue from this message only. If it is possible can you upload part of your code which could reproduce the issue?

Hi, updated the issue with some code.

**Comment by wevertoum** [comment]
same issue here, updates?

**Comment by luissantiagodev** [comment]
any update on this?

**Comment by yoreland** [comment]
In 4.x sdk createMicrophoneAudioTrack returns Promise Object.
Can you try with something like this?

            AgoraRTC.createMicrophoneAndCameraTracks({microphoneId: microphoneId}, {cameraId: cameraId})
                .then((tracks) => {
                    this.mLocalAudioTrack = tracks[0]
                    this.mLocalVideoTrack = tracks[1]
                    this._client.publish([this.mLocalAudioTrack, this.mLocalVideoTrack])

                    resolve()
                })
                .catch(e => {
                    reject(e)
                })
