### ISSUE TITLE
求一份没有压缩的SDK

### ISSUE THREAD

**Issue by han8435762** [AgoraIO/API-Examples-Web#14]
想排查一些问题 想看sdk源码 但是没有找到未压缩的

**Comment by yoreland** [comment]
目前没有开源

**Comment by han8435762** [comment]
是否考虑开源呢 目前遇到一些诡异的问题 无法排查
比如：localVideoTrack的对象套了一层proxy之后 SDK就会自动重新publish
排查了好久 如果有未压缩的SDK的话 就很容易排查了
