### ISSUE TITLE
basicLive项目运行后，观众加入后看不到直播界面

### ISSUE THREAD

**Issue by caodaiwei** [AgoraIO/API-Examples-Web#17]
basicLive项目运行后，主播角色进入可以看到直播界面，但是观众角色加入后看不到直播界面

**Comment by yoreland** [comment]
https://webdemo.agora.io/basicLive/index.html

这个页面也可以复现么?
目前这个demo是 主播角色只发流不订阅, 观众只订阅不发流

**Comment by caodaiwei** [comment]
观众不需要发流。
我刚刚试了下这个页面，还是不行。我本地运行demo作为主播推流，进入您发的那个页面后作为观众进入频道还是看不到直播界面。

**Comment by yoreland** [comment]
> 观众不需要发流。
> 
> 我刚刚试了下这个页面，还是不行。我本地运行demo作为主播推流，进入您发的那个页面后作为观众进入频道还是看不到直播界面。

想问下是否有对应的频道号 这边后台查一下
