### ISSUE TITLE
cpu and memory usage 90% 

### ISSUE THREAD

**Issue by Nits7029** [AgoraIO/API-Examples-Web#21]
I am implementing Agora v4 in my application.
The live stream video quality is not good, 
Recorded live stream video has very high latency, As it happens it consumes almost 90% of cpu and memory usage. 

OS: Windows 10
Environment: Web (React).
Package details :
agora-rtc-sdk-ng:"4.5.0"
php-sdk:
https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/php

**Comment by yoreland** [comment]
Can you share one channel name when issue reproduced?
