### ISSUE TITLE
Update ReactDemo exemple

### ISSUE THREAD

**Issue by tutusouza** [AgoraIO/API-Examples-Web#24]
In API-Examples-Web/ReactDemo/src/Call.tsx, remove "audioTrack={localAudioTrack}" of line 40.

When you pass localAudioTrack to the "MediaPlayer" component, it executes localAudioTrack.play on the local audio, causing an echo. It can be confused with some kind of problem.

**Comment by yoreland** [comment]
thx for the comments we will check that

**Comment by KaiKaio** [comment]
Has this problem been solved?   This question has puzzled me for a long time...
