### ISSUE TITLE
Screen share

### ISSUE THREAD

**Issue by rajajsx** [AgoraIO/API-Examples-Web#28]
i have implemented the Agora RTC video call and i tried to implement the screen share functionality with this
let defaultConfig = {
streamID: uid,
audio: true,
video: false,
screen: true,
};
let stream = AgoraRTC.createStream(defaultConfig);
and i can able to share the screen of User 1 but, i couldn't get the screen stream in the other User 2 window.
can someone help me to fix this issue, thanks in advance.

**Comment by plutoless** [comment]
as i commented in the other thread. please double check if you have published the stream

**Comment by rajajsx** [comment]
@plutoless  can you please share the thread link which you have answered.
