### ISSUE TITLE
Uncaught (in promise) TypeError: a is not a function while joining the channel with JOIN function

### ISSUE THREAD

**Issue by Sanchit-BigStep** [AgoraIO/API-Examples-Web#41]
Agora sdk Version :- 4.8.2

Getting the above error which joining the channel.

Attaching the file link and error trace logs below

Browser.js Formated link :- https://drive.google.com/file/d/1az01QPOmPZddo9JMoC0ptTrsxCK_6MLS/view?usp=sharing

Error :- 
Uncaught (in promise) TypeError: a is not a function
    at browser.js:formatted:14644:34
<div tabindex="-1" class="console-message-wrapper console-error-level console-selected" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: var(--override-error-border-color); border-bottom: 1px solid transparent; background-color: var(--override-console-error-background-color);"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" aria-label="browser.js:formatted:14644 Uncaught (in promise) TypeError: a is not a function
    at browser.js:formatted:14644:34 Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: dejavu sans mono, monospace; --source-code-font-size: 11px; --source-code-font-family: dejavu sans mono, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | (anonymous) | @ | browser.js:formatted:14644
-- | -- | -- | --
  | await in (anonymous) (async) |   |  
  | t | @ | browser.js:formatted:5745
  | qR | @ | browser.js:formatted:14630
  | (anonymous) | @ | browser.js:formatted:25331
  | (anonymous) | @ | browser.js:formatted:25341
  | (anonymous) | @ | browser.js:formatted:25313
  | updateConfigDistribute | @ | browser.js:formatted:25379
  | await in updateConfigDistribute (async) |   |  
  | startGetConfigDistribute | @ | browser.js:formatted:25279
  | join | @ | browser.js:formatted:46744
  | await in join (async) |   |  
  | (anonymous) | @ | browser.js:formatted:72207
  | l | @ | browser.js:formatted:72631
  | (anonymous) | @ | browser.js:formatted:72609
  | (anonymous) | @ | browser.js:formatted:72661
  | r | @ | browser.js:formatted:1412
  | a | @ | browser.js:formatted:1426
  | (anonymous) | @ | browser.js:formatted:1431
  | (anonymous) | @ | browser.js:formatted:1423
  | (anonymous) | @ | browser.js:formatted:72283
  | (anonymous) | @ | browser.js:formatted:5253
  | n | @ | browser.js:formatted:279
  | value | @ | browser.js:formatted:5249
  | value | @ | browser.js:formatted:4100
  | (anonymous) | @ | browser.js:formatted:4194
  | n | @ | browser.js:formatted:279
  | value | @ | browser.js:formatted:4177
  | start | @ | demo.js:176
  | onclick | @ | demo.html:50

</span></div></div></div></div></div><div tabindex="-1" class="console-message-wrapper console-from-api console-info-level" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: var(--override-error-border-color); border-bottom: 1px solid transparent;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; flex: 1 1 auto; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px; color: rgb(48, 57, 66); font-family: &quot;dejavu sans mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="devtools-link" role="link" tabindex="-1" title="http://127.0.0.1:5500/dist/browser.js:formatted:176" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;"></span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(48, 57, 66); font-family: &quot;dejavu sans mono&quot;, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">

**Comment by yoreland** [comment]
Hi, which browser version are you running on?

**Comment by Sanchit-BigStep** [comment]
Google Chrome Version 98.0.4758.80 (Official Build) (64-bit)
OS:- Linux Ubuntu 21.10

**Comment by Sanchit-BigStep** [comment]
> Hi, which browser version are you running on?
Google Chrome Version 98.0.4758.80 (Official Build) (64-bit)
OS:- Linux Ubuntu 21.10

**Comment by yoreland** [comment]
Hi, currently we have some difficulties to reproduce the issue. Can you help provide more information as follows:
Can you reproduce this issue on other OS rather than Ubuntu?
Did you try the https://webdemo.agora.io/basicVideoCall/index.html on the same environment?

**Comment by Sanchit-BigStep** [comment]
Closing the issue. The issue resolved on its own. I am not facing this issue anymore.
