### ISSUE TITLE
怎么建立通道

### ISSUE THREAD

**Issue by xubaobao19940428** [AgoraIO/API-Examples-Web#50]
您好，我这边项目启动起来了，也申请了AppId和token,但是怎么去生成通道呢？
![image](https://user-images.githubusercontent.com/39545419/160573353-240018df-7f9a-4d6f-84ae-d7f664175625.png)

**Comment by yoreland** [comment]
主播和观众都加入同一个channel就行了,
测试的话,可以不用开启动态appid, 这样openlive只需要配置 appid, channel可以随便设置

**Comment by xubaobao19940428** [comment]
好的，谢谢
