### ISSUE TITLE
OpenLive can't run

### ISSUE THREAD

**Issue by iceshou** [AgoraIO/API-Examples-Web#58]
我在 .env 中填入我的项目的appid和临时token，并且chaner name 也是对的。但是demo一直提示说token无效

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/5445667/173321922-e4243e20-f888-43c5-9037-32e266a113ef.png">

**Comment by plutoless** [comment]
@iceshou 您的token是怎么生成的呢
同样的token和uid，使用这个demo是否可以成功?
https://webdemo.agora.io/basicVideoCall/index.html

**Comment by iceshou** [comment]
> 



> @iceshou 您的token是怎么生成的呢 同样的token和uid，使用这个demo是否可以成功? https://webdemo.agora.io/basicVideoCall/index.html

@plutoless 我就是在控制台生成的临时token。
你给我的这个地址中可以使用：
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/5445667/173507599-310e5fe5-7ef0-4b99-b984-42aba0a2a6ae.png">

生成的token的方式：
<img width="694" alt="image" src="https://user-images.githubusercontent.com/5445667/173507696-601ffa3f-8199-4d24-ba45-57e22ff93982.png">

**Comment by plutoless** [comment]
那就说明token本身是好的，您方便在这里打个断点，看下参数传递是否和您设置的匹配吗?
https://github.com/AgoraIO/API-Examples-Web/blob/f304ecf125648e4c4f9af070fdcd37f87fbd33c7/OpenLive/src/pages/meeting.jsx#L111
