### ISSUE TITLE
CAN_NOT_GET_GATEWAY_SERVER: dynamic use static key

### ISSUE THREAD

**Issue by neilyoung** [AgoraIO/API-Examples-Web#82]
Got some credentials from a colleague, trusted them :)

Create Client. OK
Join Channel brings this:

```
AgoraRTC_N.js:5 15:54:58:287 Agora-SDK [ERROR]: [client-be997] join number: 1, Joining channel failed, rollback AgoraRTCException: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: flag: 4096, message: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: dynamic use static key
    at cA (https://download.agora.io/sdk/release/AgoraRTC_N.js:6:19351)
    at e.gatewayInfo.rI.joinChooseServer.lts (https://download.agora.io/sdk/release/AgoraRTC_N.js:6:16937)
    at async https://download.agora.io/sdk/release/AgoraRTC_N.js:5:139507

index.js:63 AgoraRTCException: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: flag: 4096, message: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: dynamic use static key
    at cA (https://download.agora.io/sdk/release/AgoraRTC_N.js:6:19351)
    at e.gatewayInfo.rI.joinChooseServer.lts (https://download.agora.io/sdk/release/AgoraRTC_N.js:6:16937)
    at async https://download.agora.io/sdk/release/AgoraRTC_N.js:5:139507
```

**Comment by plutoless** [comment]
please read the docs to understand how to sign tokens when you join channel. you are trying to use appid only to join a channel for projects which has token on.

**Comment by neilyoung** [comment]
yepp, I have that token too, but where to provide that?

**Comment by neilyoung** [comment]
I believe he forgot to provide me the certificate...

**Comment by plutoless** [comment]
if you are talking about this demo, you will need the project appid, app certificate and configure them in left menu top item.

**Comment by plutoless** [comment]
you are right.

**Comment by neilyoung** [comment]
OK, thanks. Got that working. Found, that I had an own account with you. Took the settings from there - works.

Thanks

**Comment by neilyoung** [comment]
On additional question, if allowed: In order to subscribe to my own publication I need to provide a UserID. But for some reasons I'm not able to enter a userID for the publisher. The cursor weirdly jumps back to the beginning in the edit field. Any idea?

**Comment by neilyoung** [comment]
OK, another issue here, but the reason for the jumpy behaviour of the userID input field is this regexp:

```
              <input class="form-control" id="uid" class="form-control" type="text"
                onkeyup="this.value=this.value.replace(/[^0-9]/g,'')"
                onafterpaste="this.value=this.value.replace(/[^0-9]/g,'')" placeholder="Enter the user ID">
            </div>

```

Removed it all and now I can enter something. Wondering, should only effect numbers at the first glance, but I didn't enter numbers...

**Comment by neilyoung** [comment]
But looks like I don't need that userId at all (for the moment)

**Comment by plutoless** [comment]
uid is required to be numbers. if you don't enter it, a random one will be used.

**Comment by neilyoung** [comment]
I'm opening a new issue. The regexp is behaving nuts.

**Comment by neilyoung** [comment]
Oh, yes, shame on me... Sorry.
