### ISSUE TITLE
Trying to provide a userId fails

### ISSUE THREAD

**Issue by neilyoung** [AgoraIO/API-Examples-Web#83]
Here a video showing the behaviour:

https://www.youtube.com/watch?v=nuE5k60gJv8

IMHO the regexp applied to the input is the problem here (even though I don't enter numbers at all)

```
          <div>
              <input class="form-control" id="uid" class="form-control" type="text"
                onkeyup="this.value=this.value.replace(/[^0-9]/g,'')"
                onafterpaste="this.value=this.value.replace(/[^0-9]/g,'')" placeholder="Enter the user ID">
            </div>

```

Removed that and can enter a UID

**Comment by neilyoung** [comment]
Wait. Are you expecting to see NUMBERS only?

**Comment by plutoless** [comment]
![image](https://github.com/AgoraIO/API-Examples-Web/assets/471561/48defb2c-7111-4577-a0c4-50b5ef17f672)

**Comment by neilyoung** [comment]
Yes, my bad sorry.

**Comment by neilyoung** [comment]
PS: Thanks for the _VERY_ quick response. Must be late already over there?

**Comment by plutoless** [comment]
it's ok :) just wondering around right in time.

**Comment by neilyoung** [comment]
Thanks again for your assist and time
