### ISSUE TITLE
Cannot join with self-generated token

### ISSUE THREAD

**Issue by neilyoung** [AgoraIO/API-Examples-Web#85]
First, I'm patching around in a Vue app, currently not exactly knowing, what I'm doing.

The (inherited) source code contains lines like this:

```
  agoraClient.setClientRole('audience', { level: 2 })
  if (agoraClient.connectionState === 'DISCONNECTED') {
    await agoraClient.join(agoraPara.appid, agoraPara.channel, agoraPara.token.toString())
  }
```

The join works and later on the code continues to subscribe to a stream, magically published by -- I need to say -- "somebody else", because that "somebody else" is some code in a DJI Pilot2 app, which is NOT accessible to me.

```
agoraClient.on('user-published', async (user: IAgoraRTCRemoteUser, mediaType: 'audio' | 'video') => {
    await agoraClient.subscribe(user, mediaType)
    if (mediaType === 'video') {
      console.log('subscribe success')
      // Get `RemoteVideoTrack` in the `user` object.
      const remoteVideoTrack = user.videoTrack!
      // Dynamically create a container in the form of a DIV element for playing the remote video track.
      remoteVideoTrack.play(document.getElementById('player') as HTMLElement)
    }
  })
```

At least the join works with the temp token from the Agora console and the subscribe too. The userID used by the publisher is 123456 (number), no idea, where this is taken from.

Now I started to generate my own token using JS code. I already managed to join with this token, but I don't currently get the role of the UID in the token. 

- The join does not work, if I join without the uid, which is also used to generate the token with buildTokenWithUid. I got it 1 or 2 times to work, when I joined specifiying the UID, but most the time I get:

```
AgoraRTC_N-production.js:14 Uncaught (in promise) AgoraRTCException: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: flag: 4096, message: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: invalid token, authorized failed
    at SJ (https://app.ca-test.votix.com/node_modules/.vite/agora-rtc-sdk-ng.js?v=c5087107:12143:418)
    at https://app.ca-test.votix.com/node_modules/.vite/agora-rtc-sdk-ng.js?v=c5087107:12120:48
    at Generator.next (<anonymous>)
    at fulfilled (https://app.ca-test.votix.com/node_modules/.vite/chunk-N2UNTUOU.js?v=c5087107:67:24)

```
- Tokens generated with buildTokenWithUserAccount don't work at all.

I currently have no idea anymore, how to make my tokens work.

Do you?

**Comment by plutoless** [comment]
sorry i saw you reopen the issue. does the issue persists?

**Comment by neilyoung** [comment]
No, thanks for asking. I was tricked by the fact, that a token with "valid" UID (!= 0) needs to be uniquely used in the "room".

Thanks
