### ISSUE TITLE
web端 视频通话 浏览器支持到2k吗？

### ISSUE THREAD

**Issue by shi-nn** [AgoraIO/API-Examples-Web#9]
视频通话 2k画质  目前都什么平台支持呢？

**Comment by yoreland** [comment]
web端和native端默认支持的最大摄像头采集的分辨率都是只到1080p的.

**Comment by yoreland** [comment]
请参考文档:
https://docs.agora.io/cn/Interactive%20Broadcast/API%20Reference/web/v4.2.1/globals.html#videoencoderconfigurationpreset
